/*
 * MorphingFrame.java
 *
 * Created on August 26, 2007, 11:18 AM
 */

package main;

import java.awt.Color;
import java.util.Vector;
import javax.media.jai.PlanarImage;
import javax.swing.JComboBox;

/**
 *
 * @author  Administrator
 */
public class MorphingFrame extends javax.swing.JFrame {
    
    
    //Variable Declaration
    
    
    private Vector sourceFileList;
    private Vector fileNameList;
    private JComboBox firstImageCombo;
    private JComboBox secondImageCombo;
    private ImageControl secondImageControl;
    private ImageControl firstImageControl;
    private ChildWindow currentChildWindow;
    private PlanarImage planarImage;
    private int originalHeight;
    private int originalWidth;
    private double newWidth;
    private double newHeight;
    private ChildWindow viewWindow=null;
    public  Thread thread;
    public  ProgressBar progressBar;
    public ImageProcessor imageProcessor;
    private FileCopy fileCopy;
  
    /** Creates new form MorphingFrame */
    public MorphingFrame() {
        initComponents();
        setDefaultLookAndFeelDecorated(true);
        getContentPane().setBackground(new Color(221,224,225));
       
        //Set Image Control
        firstImageControl=new ImageControl();
        firstImageControl.setBounds(55, 65, 130,100);
        getContentPane().add(firstImageControl);
        secondImageControl=new ImageControl();
        secondImageControl.setBounds(335, 65, 130,100);
        getContentPane().add(secondImageControl);
        imageProcessor=new ImageProcessor();
       fileCopy=new FileCopy();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        group1 = new javax.swing.ButtonGroup();
        firstImgLbl = new javax.swing.JLabel();
        secondImgLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstImageWidthHeightLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        secodImageWidthHeightLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        slidesTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Morphing");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        firstImgLbl.setFont(new java.awt.Font("Verdana", 1, 10));
        firstImgLbl.setText("First Image :");
        getContentPane().add(firstImgLbl);
        firstImgLbl.setBounds(70, 20, 74, 14);

        secondImgLbl.setFont(new java.awt.Font("Verdana", 1, 10));
        secondImgLbl.setText("Second Image :");
        getContentPane().add(secondImgLbl);
        secondImgLbl.setBounds(350, 20, 89, 14);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 10));
        jLabel5.setText("Resolution :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(335, 170, 67, 14);

        firstImageWidthHeightLbl.setFont(new java.awt.Font("Verdana", 1, 10));
        getContentPane().add(firstImageWidthHeightLbl);
        firstImageWidthHeightLbl.setBounds(150, 168, 90, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 10));
        jLabel7.setText("Resolution :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(55, 170, 67, 14);

        secodImageWidthHeightLbl.setFont(new java.awt.Font("Verdana", 1, 10));
        getContentPane().add(secodImageWidthHeightLbl);
        secodImageWidthHeightLbl.setBounds(420, 168, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Slide Setting");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 194, 100, 14);

        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 202, 170, 2);

        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(292, 200, 190, 2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("No. Of Slides");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(210, 220, 80, 14);

        jSeparator5.setPreferredSize(new java.awt.Dimension(52, 10));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(180, 240, 140, 2);

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 10));
        jLabel17.setText("Slides :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(190, 260, 40, 14);

        getContentPane().add(slidesTxt);
        slidesTxt.setBounds(230, 260, 70, 20);

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 10));
        jLabel18.setText("ms");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(300, 260, 17, 14);

        cancelBtn.setFont(new java.awt.Font("Verdana", 1, 10));
        cancelBtn.setText("Cancel");
        cancelBtn.setPreferredSize(new java.awt.Dimension(67, 23));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(240, 340, 80, 23);

        viewBtn.setFont(new java.awt.Font("Verdana", 1, 10));
        viewBtn.setText("View...");
        viewBtn.setPreferredSize(new java.awt.Dimension(67, 23));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        getContentPane().add(viewBtn);
        viewBtn.setBounds(160, 340, 80, 23);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(30, 202, 2, 130);

        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(30, 332, 450, 2);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(480, 202, 2, 130);

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator15);
        jSeparator15.setBounds(180, 240, 10, 50);

        getContentPane().add(jSeparator16);
        jSeparator16.setBounds(180, 290, 140, 2);

        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator17);
        jSeparator17.setBounds(320, 240, 2, 50);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-519)/2, (screenSize.height-440)/2, 519, 440);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private int getSelectedPathIndex(String fileName) {
        int index;
        for( index=0;index<fileNameList.size();index++) {
            
            if(fileName.equals((String)fileNameList.elementAt(index))) {
                
                break;
            }
        }
        return index;
    }
    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
         progressBar=new ProgressBar(); 
         progressBar.setVisible(true);
         int firstIndex=getSelectedPathIndex(firstImageCombo.getSelectedItem().toString());
         int secondIndex=getSelectedPathIndex(secondImageCombo.getSelectedItem().toString());
         String firstFilePath=(String) sourceFileList.elementAt(firstIndex);
         String secondFilePath=(String) sourceFileList.elementAt(secondIndex);
         fileCopy.deleteFiles("c:\\temp");
         imageProcessor.createMorphFiles(firstFilePath,secondFilePath,"c:\\temp",Integer.parseInt(slidesTxt.getText()),progressBar); 
      
    }//GEN-LAST:event_viewBtnActionPerformed
    
   
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed
               
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MorphingFrame().setVisible(true);
            }
        });
    }
    
    
    void setFirstComboBoxImage(String comboPath) {
        
        JAIImageReader reader=new JAIImageReader(comboPath);
        PlanarImage planarImage=reader.getPlanarImage();
        firstImageControl.setPlanarImage(planarImage);
        firstImageControl.refresh();
        originalWidth=planarImage.getWidth();
        originalHeight=planarImage.getHeight();
        firstImageWidthHeightLbl.setText(originalWidth+" x "+originalHeight);
        secodImageWidthHeightLbl.setText(originalWidth+" x "+originalHeight);
        
    }
    
    void setSecondComboBoxImage(String comboPath) {
        JAIImageReader reader=new JAIImageReader(comboPath);
        PlanarImage planarImage=reader.getPlanarImage();
        secondImageControl.setPlanarImage(planarImage);
        secondImageControl.refresh();
        originalWidth=planarImage.getWidth();
        originalHeight=planarImage.getHeight();
        secodImageWidthHeightLbl.setText(originalWidth+" x "+originalHeight);
        secodImageWidthHeightLbl.setText(originalWidth+" x "+originalHeight);
    }
    
    
    void setDefaultComboBoxImage(String comboPath) {
        setFirstComboBoxImage(comboPath);
        setSecondComboBoxImage(comboPath);
        
    }
    
     public void setSourceFileList(Vector sourceFileList) {
        this.sourceFileList = sourceFileList;
        loadComboBox();
    }

    
    private void loadComboBox() {
        fileNameList=new Vector();
        
        for(int i=0;i<sourceFileList.size();i++) {
            String fileName=(String)sourceFileList.elementAt(i);
            fileName=fileName.substring(fileName.lastIndexOf("\\")+1);
            fileNameList.addElement(fileName);
        }
        
        firstImageCombo = new javax.swing.JComboBox();
        firstImageCombo.setBackground(new java.awt.Color(221, 224, 225));
        firstImageCombo.setFont(new java.awt.Font("Verdana", 0, 10));
        firstImageCombo.setModel(new javax.swing.DefaultComboBoxModel(fileNameList));
        getContentPane().add(firstImageCombo);
        firstImageCombo.setBounds(55, 40, 130, 20);
        setDefaultComboBoxImage((String)sourceFileList.elementAt(0));
        
        firstImageCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                
                String comboBoxItem=evt.getItem().toString();
                
                setFirstComboBoxImage((String)sourceFileList.elementAt(getSelectedPathIndex(comboBoxItem)));
                
                
            }
        });

        secondImageCombo = new javax.swing.JComboBox();
        secondImageCombo.setBackground(new java.awt.Color(221, 224, 225));
        secondImageCombo.setFont(new java.awt.Font("Verdana", 0, 10));
        secondImageCombo.setModel(new javax.swing.DefaultComboBoxModel(fileNameList));
        getContentPane().add(secondImageCombo);
        secondImageCombo.setBounds(335, 40, 130, 20);
        
        secondImageCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                String comboBoxItem=evt.getItem().toString();
                setSecondComboBoxImage((String)sourceFileList.elementAt(getSelectedPathIndex(comboBoxItem)));

            }
        });
        
        
        
        
    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel firstImageWidthHeightLbl;
    private javax.swing.JLabel firstImgLbl;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel secodImageWidthHeightLbl;
    private javax.swing.JLabel secondImgLbl;
    private javax.swing.JTextField slidesTxt;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
  
}
