package main;

import javax.swing.JFrame;
import javax.swing.JProgressBar;
import javax.swing.Timer;
/*
 * ProgressBar.java
 *
 * Created on October 3, 2007, 6:56 PM
 */

/**
 *
 * @author Administrator
 */
public class ProgressBar extends javax.swing.JFrame {

   
    /**
     * Creates new form ProgressBar
     */
    public ProgressBar() {
        initComponents();
        JFrame.setDefaultLookAndFeelDecorated(true);
       
        
    }
    public void setImageProgressBar(int value)
    {
    imageProgressBar.setValue(value);    
    }
    

 public int getImageProgressBar()
    {
   return imageProgressBar.getValue();
    }
   
       public void setProgressBarStatus(int value)
    {
     progressStatus.setText(value+" %");   
    }
    

 
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        imageProgressBar = new javax.swing.JProgressBar();
        progressStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generating View");
        setAlwaysOnTop(true);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(progressStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(imageProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-510)/2, (screenSize.height-121)/2, 510, 121);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar imageProgressBar;
    private javax.swing.JLabel progressStatus;
    // End of variables declaration//GEN-END:variables
    
}
