/*
 * ColorEffectWindow.java
 *
 * Created on August 24, 2007, 12:04 AM
 */

package main;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author  Admin
 */
public class ShearSliderWindow extends javax.swing.JFrame {
    
    public final static int HORIZONTAL=0;
    
    public final static int VERTICAL=1;
    
    private int sliderValue=1;
    
    private MainFrame parent;
    
    private int type=HORIZONTAL;
    /**
     * Creates new form ColorEffectWindow
     */
    public ShearSliderWindow() {
        initComponents();
        setDefaultLookAndFeelDecorated(true);
        getContentPane().setBackground(new Color(221,224,225));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        jSlider1 = new javax.swing.JSlider();
        cancelBtn = new javax.swing.JButton();
        applyBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        
        getContentPane().setLayout(null);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Blue Effect");
        setAlwaysOnTop(true);
        setResizable(false);
        jSlider1.setFont(new java.awt.Font("Verdana", 1, 11));
        jSlider1.setValue(1);
        jSlider1.setMinimum(1);
        jSlider1.setMaximum(180);
        jSlider1.setAutoscrolls(true);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        
        getContentPane().add(jSlider1);
        jSlider1.setBounds(40, 30, 250, 25);
        
        cancelBtn.setFont(new java.awt.Font("Verdana", 1, 11));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(120, 90, 80, 23);
        
        applyBtn.setFont(new java.awt.Font("Verdana", 1, 11));
        applyBtn.setText("Apply");
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });
        
        getContentPane().add(applyBtn);
        applyBtn.setBounds(200, 90, 80, 23);
        
        okBtn.setFont(new java.awt.Font("Verdana", 1, 11));
        okBtn.setText("Ok");
        okBtn.setPreferredSize(new java.awt.Dimension(65, 23));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        
        getContentPane().add(okBtn);
        okBtn.setBounds(40, 90, 80, 23);
        
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel1.setText("%");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 35, 20, 15);
        
        show.setFont(new java.awt.Font("Verdana", 1, 11));
        getContentPane().add(show);
        show.setBounds(140, 60, 60, 10);
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-324)/2, (screenSize.height-170)/2, 324, 170);
    }// </editor-fold>
    
    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {
        parent.applyShearEffect(getType(), getSliderValue());
    }
    
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }
    
    public int getSliderValue() {
        return sliderValue;
    }
   
    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {
// TODO add your handling code here
        sliderValue=jSlider1.getValue();
        show.setText(sliderValue+"%");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setDefaultLookAndFeelDecorated(true);
                new ColorEffectWindow().setVisible(true);
            }
        });
    }
    public void setParent(JFrame parent) {
        this.parent=(MainFrame)parent;
    }
    // Variables declaration - do not modify
    private javax.swing.JButton applyBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel show;
    // End of variables declaration

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }
    
}
