package main;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.Timer;
/*
 * SplashScreen.java
 *
 * Created on February 26, 2007, 7:56 PM
 */

/**
 *
 * @author  Administrator
 */
public class SplashScreen extends javax.swing.JDialog implements ActionListener{
    
    /** Creates new form SplashScreen */
    public SplashScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        timer=new Timer(500,this);
        timer.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        splashLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        splashLabel.setIcon(new javax.swing.ImageIcon("splash.jpg"));
        getContentPane().add(splashLabel, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }// </editor-fold>//GEN-END:initComponents
    
  
    public void actionPerformed(ActionEvent ae)
    {
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel splashLabel;
    // End of variables declaration//GEN-END:variables
    private Timer timer;
}
